const tests = [
  {
    id: 65,
    name: "Die Gebrüder Grimm",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "D" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Ende d" },
        { type: "missing", officialAnswers: ["es"] },
        { type: "text", value: " siebzehnten Jahrhund" },
        { type: "missing", officialAnswers: ["erts"] },
        { type: "text", value: " geborenen Brü" },
        { type: "missing", officialAnswers: ["der"] },
        { type: "text", value: " Jacob u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Wilhelm Gri" },
        { type: "missing", officialAnswers: ["mm"] },
        { type: "text", value: " sind vie" },
        { type: "missing", officialAnswers: ["len"] },
        { type: "text", value: " Deutschen vorwi" },
        { type: "missing", officialAnswers: ["egend"] },
        { type: "text", value: " als Verfa" },
        { type: "missing", officialAnswers: ["sser"] },
        { type: "text", value: " der Märchensamm" },
        { type: "missing", officialAnswers: ["lung"] },
        { type: "text", value: " „Kinder- u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Hausmärchen“ beka" },
        { type: "missing", officialAnswers: ["nnt"] },
        { type: "text", value: ". Was vie" },
        { type: "missing", officialAnswers: ["len"] },
        { type: "text", value: " ihrer Le" },
        { type: "missing", officialAnswers: ["ser"] },
        { type: "text", value: " jedoch weni" },
        { type: "missing", officialAnswers: ["ger"] },
        { type: "text", value: " bewusst i" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: ", sind ih" },
        { type: "missing", officialAnswers: ["re"] },
        { type: "text", value: " Verdienste u" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " die deut" },
        { type: "missing", officialAnswers: ["sche"] },
        { type: "text", value: " Sprache, a" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " der ih" },
        { type: "missing", officialAnswers: ["nen"] },
        { type: "text", value: " als Sprachwissensc" },
        { type: "missing", officialAnswers: ["haftler"] },
        { type: "text", value: " sehr vi" },
        { type: "missing", officialAnswers: ["el"] },
        { type: "text", value: " gelegen w" },
        { type: "missing", officialAnswers: ["ar"] },
        { type: "text", value: ". So zeic" },
        { type: "missing", officialAnswers: ["hnen"] },
        { type: "text", value: " die a" },
        { type: "missing", officialAnswers: ["us"] },
        { type: "text", value: " Hanau stamm" },
        { type: "missing", officialAnswers: ["enden"] },
        { type: "text", value: " Brüder Gri" },
        { type: "missing", officialAnswers: ["mm"] },
        { type: "text", value: " beispielsweise f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " die Erstel" },
        { type: "missing", officialAnswers: ["lung"] },
        { type: "text", value: " der ers" },
        { type: "missing", officialAnswers: ["ten"] },
        { type: "text", value: " deutschen Gram" },
        { type: "missing", officialAnswers: ["matik"] },
        { type: "text", value: " verantwortlich. D" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " eine d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Brüder, Ja" },
        { type: "missing", officialAnswers: ["cob"] },
        { type: "text", value: ", machte si" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " dabei insbes" },
        { type: "missing", officialAnswers: ["ondere"] },
        { type: "text", value: " mit d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Erforschung d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " indogermanischen Sprachherk" },
        { type: "missing", officialAnswers: ["unft"] },
        { type: "text", value: " des Deuts" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " einen Na" },
        { type: "missing", officialAnswers: ["men"] },
        { type: "text", value: ". Die Tats" },
        { type: "missing", officialAnswers: ["ache"] },
        { type: "text", value: ", dass e" },
        { type: "missing", officialAnswers: ["s"] },
        { type: "text", value: " heute i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " beinahe je" },
        { type: "missing", officialAnswers: ["der"] },
        { type: "text", value: " Stadt ei" },
        { type: "missing", officialAnswers: ["ne"] },
        { type: "text", value: " Gebrüder-Grimm-Sch" },
        { type: "missing", officialAnswers: ["ule"] },
        { type: "text", value: " gibt, verdeu" },
        { type: "missing", officialAnswers: ["tlicht"] },
        { type: "text", value: " ihre imme" },
        { type: "missing", officialAnswers: ["nse"] },
        { type: "text", value: " Bedeutung für das deutsche Kulturgut." },
      ],
    },
  },
  {
    id: 66,
    name: "PKW-Maut",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Maut, s" },
        { type: "missing", officialAnswers: ["o"] },
        { type: "text", value: " nennt si" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " in Deutschla" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " eine allge" },
        { type: "missing", officialAnswers: ["meine"] },
        { type: "text", value: " Abgabe, d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " zur Nutz" },
        { type: "missing", officialAnswers: ["ung"] },
        { type: "text", value: " des Autobahnnet" },
        { type: "missing", officialAnswers: ["zes"] },
        { type: "text", value: " mit Kraftfahrzeu" },
        { type: "missing", officialAnswers: ["gen"] },
        { type: "text", value: " berechtigt. Vi" },
        { type: "missing", officialAnswers: ["ele"] },
        { type: "text", value: " Länder Euro" },
        { type: "missing", officialAnswers: ["pas"] },
        { type: "text", value: " nutzen ber" },
        { type: "missing", officialAnswers: ["eits"] },
        { type: "text", value: " seit Lan" },
        { type: "missing", officialAnswers: ["gem"] },
        { type: "text", value: " diese Fo" },
        { type: "missing", officialAnswers: ["rm"] },
        { type: "text", value: " der Geb" },
        { type: "missing", officialAnswers: ["ühr,"] },
        { type: "text", value: " um d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " notwendigen Instandhaltu" },
        { type: "missing", officialAnswers: ["ngen"] },
        { type: "text", value: " ihres Straßensyst" },
        { type: "missing", officialAnswers: ["ems"] },
        { type: "text", value: " zu finanz" },
        { type: "missing", officialAnswers: ["ieren"] },
        { type: "text", value: ". In d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Bundesrepublik gi" },
        { type: "missing", officialAnswers: ["bt"] },
        { type: "text", value: " es d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Maut jed" },
        { type: "missing", officialAnswers: ["och"] },
        { type: "text", value: " bislang n" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " für LK" },
        { type: "missing", officialAnswers: ["Ws."] },
        { type: "text", value: " Ab 2016 sol" },
        { type: "missing", officialAnswers: ["lte"] },
        { type: "text", value: " nun na" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " Plänen d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Regierung au" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " für PK" },
        { type: "missing", officialAnswers: ["Ws"] },
        { type: "text", value: " eine Ma" },
        { type: "missing", officialAnswers: ["ut"] },
        { type: "text", value: " eingeführt wer" },
        { type: "missing", officialAnswers: ["den"] },
        { type: "text", value: ", um d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " marode Finanz" },
        { type: "missing", officialAnswers: ["ierung"] },
        { type: "text", value: " der deuts" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " Autobahnen aufzube" },
        { type: "missing", officialAnswers: ["ssern"] },
        { type: "text", value: ". Kritiker wand" },
        { type: "missing", officialAnswers: ["ten"] },
        { type: "text", value: " jedoch e" },
        { type: "missing", officialAnswers: ["in"] },
        { type: "text", value: ", dass d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Art u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Weise d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Abgabe kei" },
        { type: "missing", officialAnswers: ["ne"] },
        { type: "text", value: " effektive Aufbes" },
        { type: "missing", officialAnswers: ["serung"] },
        { type: "text", value: " der Fina" },
        { type: "missing", officialAnswers: ["nzen"] },
        { type: "text", value: " des Verkehrsminist" },
        { type: "missing", officialAnswers: ["eriums"] },
        { type: "text", value: " zur Fo" },
        { type: "missing", officialAnswers: ["lge"] },
        { type: "text", value: " haben we" },
        { type: "missing", officialAnswers: ["rde"] },
        { type: "text", value: ". Zud" },
        { type: "missing", officialAnswers: ["em"] },
        { type: "text", value: " wird inzwi" },
        { type: "missing", officialAnswers: ["schen"] },
        { type: "text", value: " die Rechtmäß" },
        { type: "missing", officialAnswers: ["igkeit"] },
        { type: "text", value: " der Ma" },
        { type: "missing", officialAnswers: ["ut"] },
        { type: "text", value: " nach EU-Recht geprüft." },
      ],
    },
  },
  {
    id: 67,
    name: "Der Deutsche Wetterdienst",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Der Deutsche Wetterdie" },
        { type: "missing", officialAnswers: ["nst"] },
        { type: "text", value: " ist d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " nationale meteorol" },
        { type: "missing", officialAnswers: ["ogische"] },
        { type: "text", value: " Dienst f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " Deutschland u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " versorgt üb" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " seine Zent" },
        { type: "missing", officialAnswers: ["rale"] },
        { type: "text", value: " in Offenba" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " in d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Nähe v" },
        { type: "missing", officialAnswers: ["on"] },
        { type: "text", value: " Frankfurt a" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " Main Privatnut" },
        { type: "missing", officialAnswers: ["zer"] },
        { type: "text", value: " wie Institu" },
        { type: "missing", officialAnswers: ["tionen"] },
        { type: "text", value: " mit aktue" },
        { type: "missing", officialAnswers: ["llen"] },
        { type: "text", value: " Wetterdaten, d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " teils f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " spezielle Nutzergrup" },
        { type: "missing", officialAnswers: ["pen"] },
        { type: "text", value: " (wie z. B. d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Schifffahrt u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Landwirtschaft) opti" },
        { type: "missing", officialAnswers: ["miert"] },
        { type: "text", value: " aufbereitet wer" },
        { type: "missing", officialAnswers: ["den"] },
        { type: "text", value: ". Das inzwi" },
        { type: "missing", officialAnswers: ["schen"] },
        { type: "text", value: " wichtigste Med" },
        { type: "missing", officialAnswers: ["ium"] },
        { type: "text", value: " des Deuts" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " Wetterdienstes i" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: " neben d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " nach w" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " vor erreich" },
        { type: "missing", officialAnswers: ["baren"] },
        { type: "text", value: " telefonischen Weterausk" },
        { type: "missing", officialAnswers: ["unft"] },
        { type: "text", value: " wohl d" },
        { type: "missing", officialAnswers: ["as"] },
        { type: "text", value: " hauseigene Internetpor" },
        { type: "missing", officialAnswers: ["tal"] },
        { type: "text", value: ", das jeder" },
        { type: "missing", officialAnswers: ["zeit"] },
        { type: "text", value: " über Comp" },
        { type: "missing", officialAnswers: ["uter,"] },
        { type: "text", value: " Tablet u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Co. errei" },
        { type: "missing", officialAnswers: ["chbar"] },
        { type: "text", value: " ist. Ne" },
        { type: "missing", officialAnswers: ["ben"] },
        { type: "text", value: " den Wettervorher" },
        { type: "missing", officialAnswers: ["sagen"] },
        { type: "text", value: " sind üb" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " den Wetterdie" },
        { type: "missing", officialAnswers: ["nst"] },
        { type: "text", value: " auch aktu" },
        { type: "missing", officialAnswers: ["elle"] },
        { type: "text", value: " Pollenflugprognosen, lok" },
        { type: "missing", officialAnswers: ["ale"] },
        { type: "text", value: " Hitzewarnungen, d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Seewetterbericht u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " auch Unwetterwarnu" },
        { type: "missing", officialAnswers: ["ngen"] },
        { type: "text", value: " für d" },
        { type: "missing", officialAnswers: ["as"] },
        { type: "text", value: " gesamte Bundesgeb" },
        { type: "missing", officialAnswers: ["iet"] },
        { type: "text", value: " abrufbar. D" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Deutsche Wetterdie" },
        { type: "missing", officialAnswers: ["nst"] },
        { type: "text", value: " unterhält e" },
        { type: "missing", officialAnswers: ["in"] },
        { type: "text", value: " großes Messne" },
        { type: "missing", officialAnswers: ["tz"] },
        { type: "text", value: " von 1795 Wetterstationen." },
      ],
    },
  },
  {
    id: 68,
    name: "Wasserburg am Inn",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Wasserburg i" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: " eine i" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " Kreis Rosenhe" },
        { type: "missing", officialAnswers: ["im"] },
        { type: "text", value: " gelegene Kleinst" },
        { type: "missing", officialAnswers: ["adt"] },
        { type: "text", value: " in Bay" },
        { type: "missing", officialAnswers: ["ern"] },
        { type: "text", value: ", deren Stadtke" },
        { type: "missing", officialAnswers: ["rn"] },
        { type: "text", value: " Häuser i" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " venezianischen Baust" },
        { type: "missing", officialAnswers: ["il"] },
        { type: "text", value: " zieren. S" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " ist insbes" },
        { type: "missing", officialAnswers: ["ondere"] },
        { type: "text", value: " für d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " außergewöhnliche La" },
        { type: "missing", officialAnswers: ["ge"] },
        { type: "text", value: " ihres Stadtke" },
        { type: "missing", officialAnswers: ["rns"] },
        { type: "text", value: " bekannt, d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " beinahe vollst" },
        { type: "missing", officialAnswers: ["ändig"] },
        { type: "text", value: " vom Flu" },
        { type: "missing", officialAnswers: ["ss"] },
        { type: "text", value: " Inn umflo" },
        { type: "missing", officialAnswers: ["ssen"] },
        { type: "text", value: " und da" },
        { type: "missing", officialAnswers: ["her"] },
        { type: "text", value: " eigentlich n" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " über Brüc" },
        { type: "missing", officialAnswers: ["ken"] },
        { type: "text", value: " erreichbar i" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: ". Diese Tatsa" },
        { type: "missing", officialAnswers: ["che"] },
        { type: "text", value: " macht d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Stadt natü" },
        { type: "missing", officialAnswers: ["rlich"] },
        { type: "text", value: " auch se" },
        { type: "missing", officialAnswers: ["hr"] },
        { type: "text", value: " anfällig f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " Hochwasser. Wasserbu" },
        { type: "missing", officialAnswers: ["rg"] },
        { type: "text", value: " blickt a" },
        { type: "missing", officialAnswers: ["uf"] },
        { type: "text", value: " eine se" },
        { type: "missing", officialAnswers: ["hr"] },
        { type: "text", value: " lange u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " bewegte Stadtgesch" },
        { type: "missing", officialAnswers: ["ichte"] },
        { type: "text", value: " zurück u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " verfügt i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " der Altst" },
        { type: "missing", officialAnswers: ["adt"] },
        { type: "text", value: " über ei" },
        { type: "missing", officialAnswers: ["ne"] },
        { type: "text", value: " fast ausschl" },
        { type: "missing", officialAnswers: ["ießlich"] },
        { type: "text", value: " mittelalterliche Bausubs" },
        { type: "missing", officialAnswers: ["tanz"] },
        { type: "text", value: ", die si" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " auf gefüh" },
        { type: "missing", officialAnswers: ["rten"] },
        { type: "text", value: " Stadttouren entd" },
        { type: "missing", officialAnswers: ["ecken"] },
        { type: "text", value: " lässt. I" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " Mittelalter erla" },
        { type: "missing", officialAnswers: ["ngte"] },
        { type: "text", value: " Wasserburg aufg" },
        { type: "missing", officialAnswers: ["rund"] },
        { type: "text", value: " seiner La" },
        { type: "missing", officialAnswers: ["ge"] },
        { type: "text", value: " am I" },
        { type: "missing", officialAnswers: ["nn"] },
        { type: "text", value: " große Wichti" },
        { type: "missing", officialAnswers: ["gkeit"] },
        { type: "text", value: " als Umschlagpl" },
        { type: "missing", officialAnswers: ["atz"] },
        { type: "text", value: " für d" },
        { type: "missing", officialAnswers: ["en"] },
        { type: "text", value: " Salzhandel u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " war Binnenha" },
        { type: "missing", officialAnswers: ["fen"] },
        { type: "text", value: " der Stadt München." },
      ],
    },
  },
  {
    id: 69,
    name: "Smartphones und ihre gesellschaftliche Bedeutung",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "No" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " nie i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " der Menschheitsgesch" },
        { type: "missing", officialAnswers: ["ichte"] },
        { type: "text", value: " hat si" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " die techn" },
        { type: "missing", officialAnswers: ["ische"] },
        { type: "text", value: " Entwicklung der" },
        { type: "missing", officialAnswers: ["art"] },
        { type: "text", value: " beschleunigt, w" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " es i" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " ausgehenden zwanzi" },
        { type: "missing", officialAnswers: ["gsten"] },
        { type: "text", value: " und beginn" },
        { type: "missing", officialAnswers: ["enden"] },
        { type: "text", value: " einundzwanzigsten Jahrhund" },
        { type: "missing", officialAnswers: ["ert"] },
        { type: "text", value: " der Fa" },
        { type: "missing", officialAnswers: ["ll"] },
        { type: "text", value: " war. E" },
        { type: "missing", officialAnswers: ["in"] },
        { type: "text", value: " wichtiger Fo" },
        { type: "missing", officialAnswers: ["kus"] },
        { type: "text", value: " der Entwick" },
        { type: "missing", officialAnswers: ["lungen"] },
        { type: "text", value: " war u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " ist d" },
        { type: "missing", officialAnswers: ["as"] },
        { type: "text", value: " mobile Tele" },
        { type: "missing", officialAnswers: ["fon"] },
        { type: "text", value: ". Inzwischen ha" },
        { type: "missing", officialAnswers: ["ben"] },
        { type: "text", value: " sich d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " sogenannten Han" },
        { type: "missing", officialAnswers: ["dys"] },
        { type: "text", value: " zu wah" },
        { type: "missing", officialAnswers: ["ren"] },
        { type: "text", value: " Alleskönnern entwi" },
        { type: "missing", officialAnswers: ["ckelt"] },
        { type: "text", value: ", die m" },
        { type: "missing", officialAnswers: ["it"] },
        { type: "text", value: " einem einf" },
        { type: "missing", officialAnswers: ["achen"] },
        { type: "text", value: " Gerät z" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " Durchführung v" },
        { type: "missing", officialAnswers: ["on"] },
        { type: "text", value: " Telefonanrufen nic" },
        { type: "missing", officialAnswers: ["hts"] },
        { type: "text", value: " mehr gemei" },
        { type: "missing", officialAnswers: ["nsam"] },
        { type: "text", value: " haben. Mens" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " haben ih" },
        { type: "missing", officialAnswers: ["re"] },
        { type: "text", value: " Smartphones übe" },
        { type: "missing", officialAnswers: ["rall"] },
        { type: "text", value: " dabei, füh" },
        { type: "missing", officialAnswers: ["len"] },
        { type: "text", value: " sich so" },
        { type: "missing", officialAnswers: ["gar"] },
        { type: "text", value: " „nackt“ od" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " „von d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Umwelt abgeschn" },
        { type: "missing", officialAnswers: ["itten"] },
        { type: "text", value: " “, wenn s" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " es ein" },
        { type: "missing", officialAnswers: ["mal"] },
        { type: "text", value: " vergessen. Insbes" },
        { type: "missing", officialAnswers: ["ondere"] },
        { type: "text", value: " für Jugen" },
        { type: "missing", officialAnswers: ["dliche"] },
        { type: "text", value: " entwickelt si" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " das Smartph" },
        { type: "missing", officialAnswers: ["one"] },
        { type: "text", value: " aber au" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " zum Prob" },
        { type: "missing", officialAnswers: ["lem"] },
        { type: "text", value: ", da d" },
        { type: "missing", officialAnswers: ["a"] },
        { type: "text", value: " Konsum d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " darüber zugäng" },
        { type: "missing", officialAnswers: ["lichen"] },
        { type: "text", value: " Medien häu" },
        { type: "missing", officialAnswers: ["fig"] },
        { type: "text", value: " einen Großte" },
        { type: "missing", officialAnswers: ["il"] },
        { type: "text", value: " ihres Tages beansprucht." },
      ],
    },
  },
  {
    id: 70,
    name: "Artgerechte Fütterung von Haustieren",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Die zuneh" },
        { type: "missing", officialAnswers: ["mende"] },
        { type: "text", value: " Industrialisierung d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Lebensmittelproduktion d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " westlichen Län" },
        { type: "missing", officialAnswers: ["der"] },
        { type: "text", value: ", der sogena" },
        { type: "missing", officialAnswers: ["nnten"] },
        { type: "text", value: " ersten We" },
        { type: "missing", officialAnswers: ["lt"] },
        { type: "text", value: ", macht au" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " vor d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Nahrung f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " unsere Hausti" },
        { type: "missing", officialAnswers: ["ere"] },
        { type: "text", value: " nicht ha" },
        { type: "missing", officialAnswers: ["lt"] },
        { type: "text", value: ": Zubereitetes Fut" },
        { type: "missing", officialAnswers: ["ter"] },
        { type: "text", value: " ist i" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " Überfluss u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " in d" },
        { type: "missing", officialAnswers: ["en"] },
        { type: "text", value: " unterschiedlichsten For" },
        { type: "missing", officialAnswers: ["men"] },
        { type: "text", value: " in Gesch" },
        { type: "missing", officialAnswers: ["äften"] },
        { type: "text", value: " für Tierfut" },
        { type: "missing", officialAnswers: ["ter"] },
        { type: "text", value: " erhältlich. E" },
        { type: "missing", officialAnswers: ["in"] },
        { type: "text", value: " Blick a" },
        { type: "missing", officialAnswers: ["uf"] },
        { type: "text", value: " die Zutatenlis" },
        { type: "missing", officialAnswers: ["ten"] },
        { type: "text", value: " enthüllt Erschre" },
        { type: "missing", officialAnswers: ["ckendes"] },
        { type: "text", value: ": Meist ha" },
        { type: "missing", officialAnswers: ["ben"] },
        { type: "text", value: " die Futtersor" },
        { type: "missing", officialAnswers: ["ten"] },
        { type: "text", value: " mit d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " artgerechten Ernäh" },
        { type: "missing", officialAnswers: ["rung"] },
        { type: "text", value: " eines Haustie" },
        { type: "missing", officialAnswers: ["res"] },
        { type: "text", value: " nicht me" },
        { type: "missing", officialAnswers: ["hr"] },
        { type: "text", value: " allzu vi" },
        { type: "missing", officialAnswers: ["el"] },
        { type: "text", value: " zu t" },
        { type: "missing", officialAnswers: ["un"] },
        { type: "text", value: ". Reine Fleischfres" },
        { type: "missing", officialAnswers: ["ser"] },
        { type: "text", value: " wie Kat" },
        { type: "missing", officialAnswers: ["zen"] },
        { type: "text", value: " erhalten i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " Fertigfutter z" },
        { type: "missing", officialAnswers: ["um"] },
        { type: "text", value: " Beispiel se" },
        { type: "missing", officialAnswers: ["hr"] },
        { type: "text", value: " häufig ei" },
        { type: "missing", officialAnswers: ["nen"] },
        { type: "text", value: " Brei a" },
        { type: "missing", officialAnswers: ["us"] },
        { type: "text", value: " Asche, Ma" },
        { type: "missing", officialAnswers: ["is"] },
        { type: "text", value: " oder So" },
        { type: "missing", officialAnswers: ["ja"] },
        { type: "text", value: " mit n" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " minimalem Fleischant" },
        { type: "missing", officialAnswers: ["eil"] },
        { type: "text", value: ". Tierhalter ge" },
        { type: "missing", officialAnswers: ["hen"] },
        { type: "text", value: " deswegen inzwi" },
        { type: "missing", officialAnswers: ["schen"] },
        { type: "text", value: " oft z" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " sogenannten Rohfütte" },
        { type: "missing", officialAnswers: ["rung"] },
        { type: "text", value: " über, u" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " ihren Tie" },
        { type: "missing", officialAnswers: ["ren"] },
        { type: "text", value: " ein mögl" },
        { type: "missing", officialAnswers: ["ichst"] },
        { type: "text", value: " artgerechtes Le" },
        { type: "missing", officialAnswers: ["ben"] },
        { type: "text", value: " zu ermög" },
        { type: "missing", officialAnswers: ["lichen"] },
        { type: "text", value: "." },
      ],
    },
  },
];
