const tests = [
  {
    id: 67,
    name: "Der Deutsche Wetterdienst",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Der Deutsche Wetterdie" },
        { type: "missing", officialAnswers: ["nst"] },
        { type: "text", value: " ist d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " nationale meteorol" },
        { type: "missing", officialAnswers: ["ogische"] },
        { type: "text", value: " Dienst f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " Deutschland u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " versorgt üb" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " seine Zent" },
        { type: "missing", officialAnswers: ["rale"] },
        { type: "text", value: " in Offenba" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " in d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Nähe v" },
        { type: "missing", officialAnswers: ["on"] },
        { type: "text", value: " Frankfurt a" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " Main Privatnut" },
        { type: "missing", officialAnswers: ["zer"] },
        { type: "text", value: " wie Institu" },
        { type: "missing", officialAnswers: ["tionen"] },
        { type: "text", value: " mit aktue" },
        { type: "missing", officialAnswers: ["llen"] },
        { type: "text", value: " Wetterdaten, d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " teils f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " spezielle Nutzergrup" },
        { type: "missing", officialAnswers: ["pen"] },
        { type: "text", value: " (wie z. B. d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Schifffahrt u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Landwirtschaft) opti" },
        { type: "missing", officialAnswers: ["miert"] },
        { type: "text", value: " aufbereitet wer" },
        { type: "missing", officialAnswers: ["den"] },
        { type: "text", value: ". Das inzwi" },
        { type: "missing", officialAnswers: ["schen"] },
        { type: "text", value: " wichtigste Med" },
        { type: "missing", officialAnswers: ["ium"] },
        { type: "text", value: " des Deuts" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " Wetterdienstes i" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: " neben d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " nach w" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " vor erreich" },
        { type: "missing", officialAnswers: ["baren"] },
        { type: "text", value: " telefonischen Weterausk" },
        { type: "missing", officialAnswers: ["unft"] },
        { type: "text", value: " wohl d" },
        { type: "missing", officialAnswers: ["as"] },
        { type: "text", value: " hauseigene Internetpor" },
        { type: "missing", officialAnswers: ["tal"] },
        { type: "text", value: ", das jeder" },
        { type: "missing", officialAnswers: ["zeit"] },
        { type: "text", value: " über Comp" },
        { type: "missing", officialAnswers: ["uter,"] },
        { type: "text", value: " Tablet u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Co. errei" },
        { type: "missing", officialAnswers: ["chbar"] },
        { type: "text", value: " ist. Ne" },
        { type: "missing", officialAnswers: ["ben"] },
        { type: "text", value: " den Wettervorher" },
        { type: "missing", officialAnswers: ["sagen"] },
        { type: "text", value: " sind üb" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " den Wetterdie" },
        { type: "missing", officialAnswers: ["nst"] },
        { type: "text", value: " auch aktu" },
        { type: "missing", officialAnswers: ["elle"] },
        { type: "text", value: " Pollenflugprognosen, lok" },
        { type: "missing", officialAnswers: ["ale"] },
        { type: "text", value: " Hitzewarnungen, d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Seewetterbericht u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " auch Unwetterwarnu" },
        { type: "missing", officialAnswers: ["ngen"] },
        { type: "text", value: " für d" },
        { type: "missing", officialAnswers: ["as"] },
        { type: "text", value: " gesamte Bundesgeb" },
        { type: "missing", officialAnswers: ["iet"] },
        { type: "text", value: " abrufbar. D" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Deutsche Wetterdie" },
        { type: "missing", officialAnswers: ["nst"] },
        { type: "text", value: " unterhält e" },
        { type: "missing", officialAnswers: ["in"] },
        { type: "text", value: " großes Messne" },
        { type: "missing", officialAnswers: ["tz"] },
        { type: "text", value: " von 1795 Wetterstationen." },
      ],
    },
  },
  {
    id: 68,
    name: "Wasserburg am Inn",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Wasserburg i" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: " eine i" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " Kreis Rosenhe" },
        { type: "missing", officialAnswers: ["im"] },
        { type: "text", value: " gelegene Kleinst" },
        { type: "missing", officialAnswers: ["adt"] },
        { type: "text", value: " in Bay" },
        { type: "missing", officialAnswers: ["ern"] },
        { type: "text", value: ", deren Stadtke" },
        { type: "missing", officialAnswers: ["rn"] },
        { type: "text", value: " Häuser i" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " venezianischen Baust" },
        { type: "missing", officialAnswers: ["il"] },
        { type: "text", value: " zieren. S" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " ist insbes" },
        { type: "missing", officialAnswers: ["ondere"] },
        { type: "text", value: " für d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " außergewöhnliche La" },
        { type: "missing", officialAnswers: ["ge"] },
        { type: "text", value: " ihres Stadtke" },
        { type: "missing", officialAnswers: ["rns"] },
        { type: "text", value: " bekannt, d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " beinahe vollst" },
        { type: "missing", officialAnswers: ["ändig"] },
        { type: "text", value: " vom Flu" },
        { type: "missing", officialAnswers: ["ss"] },
        { type: "text", value: " Inn umflo" },
        { type: "missing", officialAnswers: ["ssen"] },
        { type: "text", value: " und da" },
        { type: "missing", officialAnswers: ["her"] },
        { type: "text", value: " eigentlich n" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " über Brüc" },
        { type: "missing", officialAnswers: ["ken"] },
        { type: "text", value: " erreichbar i" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: ". Diese Tatsa" },
        { type: "missing", officialAnswers: ["che"] },
        { type: "text", value: " macht d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Stadt natü" },
        { type: "missing", officialAnswers: ["rlich"] },
        { type: "text", value: " auch se" },
        { type: "missing", officialAnswers: ["hr"] },
        { type: "text", value: " anfällig f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " Hochwasser. Wasserbu" },
        { type: "missing", officialAnswers: ["rg"] },
        { type: "text", value: " blickt a" },
        { type: "missing", officialAnswers: ["uf"] },
        { type: "text", value: " eine se" },
        { type: "missing", officialAnswers: ["hr"] },
        { type: "text", value: " lange u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " bewegte Stadtgesch" },
        { type: "missing", officialAnswers: ["ichte"] },
        { type: "text", value: " zurück u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " verfügt i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " der Altst" },
        { type: "missing", officialAnswers: ["adt"] },
        { type: "text", value: " über ei" },
        { type: "missing", officialAnswers: ["ne"] },
        { type: "text", value: " fast ausschl" },
        { type: "missing", officialAnswers: ["ießlich"] },
        { type: "text", value: " mittelalterliche Bausubs" },
        { type: "missing", officialAnswers: ["tanz"] },
        { type: "text", value: ", die si" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " auf gefüh" },
        { type: "missing", officialAnswers: ["rten"] },
        { type: "text", value: " Stadttouren entd" },
        { type: "missing", officialAnswers: ["ecken"] },
        { type: "text", value: " lässt. I" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " Mittelalter erla" },
        { type: "missing", officialAnswers: ["ngte"] },
        { type: "text", value: " Wasserburg aufg" },
        { type: "missing", officialAnswers: ["rund"] },
        { type: "text", value: " seiner La" },
        { type: "missing", officialAnswers: ["ge"] },
        { type: "text", value: " am I" },
        { type: "missing", officialAnswers: ["nn"] },
        { type: "text", value: " große Wichti" },
        { type: "missing", officialAnswers: ["gkeit"] },
        { type: "text", value: " als Umschlagpl" },
        { type: "missing", officialAnswers: ["atz"] },
        { type: "text", value: " für d" },
        { type: "missing", officialAnswers: ["en"] },
        { type: "text", value: " Salzhandel u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " war Binnenha" },
        { type: "missing", officialAnswers: ["fen"] },
        { type: "text", value: " der Stadt München." },
      ],
    },
  },
  {
    id: 69,
    name: "Smartphones und ihre gesellschaftliche Bedeutung",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "No" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " nie i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " der Menschheitsgesch" },
        { type: "missing", officialAnswers: ["ichte"] },
        { type: "text", value: " hat si" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " die techn" },
        { type: "missing", officialAnswers: ["ische"] },
        { type: "text", value: " Entwicklung der" },
        { type: "missing", officialAnswers: ["art"] },
        { type: "text", value: " beschleunigt, w" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " es i" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " ausgehenden zwanzi" },
        { type: "missing", officialAnswers: ["gsten"] },
        { type: "text", value: " und beginn" },
        { type: "missing", officialAnswers: ["enden"] },
        { type: "text", value: " einundzwanzigsten Jahrhund" },
        { type: "missing", officialAnswers: ["ert"] },
        { type: "text", value: " der Fa" },
        { type: "missing", officialAnswers: ["ll"] },
        { type: "text", value: " war. E" },
        { type: "missing", officialAnswers: ["in"] },
        { type: "text", value: " wichtiger Fo" },
        { type: "missing", officialAnswers: ["kus"] },
        { type: "text", value: " der Entwick" },
        { type: "missing", officialAnswers: ["lungen"] },
        { type: "text", value: " war u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " ist d" },
        { type: "missing", officialAnswers: ["as"] },
        { type: "text", value: " mobile Tele" },
        { type: "missing", officialAnswers: ["fon"] },
        { type: "text", value: ". Inzwischen ha" },
        { type: "missing", officialAnswers: ["ben"] },
        { type: "text", value: " sich d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " sogenannten Han" },
        { type: "missing", officialAnswers: ["dys"] },
        { type: "text", value: " zu wah" },
        { type: "missing", officialAnswers: ["ren"] },
        { type: "text", value: " Alleskönnern entwi" },
        { type: "missing", officialAnswers: ["ckelt"] },
        { type: "text", value: ", die m" },
        { type: "missing", officialAnswers: ["it"] },
        { type: "text", value: " einem einf" },
        { type: "missing", officialAnswers: ["achen"] },
        { type: "text", value: " Gerät z" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " Durchführung v" },
        { type: "missing", officialAnswers: ["on"] },
        { type: "text", value: " Telefonanrufen nic" },
        { type: "missing", officialAnswers: ["hts"] },
        { type: "text", value: " mehr gemei" },
        { type: "missing", officialAnswers: ["nsam"] },
        { type: "text", value: " haben. Mens" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " haben ih" },
        { type: "missing", officialAnswers: ["re"] },
        { type: "text", value: " Smartphones übe" },
        { type: "missing", officialAnswers: ["rall"] },
        { type: "text", value: " dabei, füh" },
        { type: "missing", officialAnswers: ["len"] },
        { type: "text", value: " sich so" },
        { type: "missing", officialAnswers: ["gar"] },
        { type: "text", value: " „nackt“ od" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " „von d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Umwelt abgeschn" },
        { type: "missing", officialAnswers: ["itten"] },
        { type: "text", value: " “, wenn s" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " es ein" },
        { type: "missing", officialAnswers: ["mal"] },
        { type: "text", value: " vergessen. Insbes" },
        { type: "missing", officialAnswers: ["ondere"] },
        { type: "text", value: " für Jugen" },
        { type: "missing", officialAnswers: ["dliche"] },
        { type: "text", value: " entwickelt si" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " das Smartph" },
        { type: "missing", officialAnswers: ["one"] },
        { type: "text", value: " aber au" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " zum Prob" },
        { type: "missing", officialAnswers: ["lem"] },
        { type: "text", value: ", da d" },
        { type: "missing", officialAnswers: ["a"] },
        { type: "text", value: " Konsum d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " darüber zugäng" },
        { type: "missing", officialAnswers: ["lichen"] },
        { type: "text", value: " Medien häu" },
        { type: "missing", officialAnswers: ["fig"] },
        { type: "text", value: " einen Großte" },
        { type: "missing", officialAnswers: ["il"] },
        { type: "text", value: " ihres Tages beansprucht." },
      ],
    },
  },
  {
    id: 70,
    name: "Artgerechte Fütterung von Haustieren",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Die zuneh" },
        { type: "missing", officialAnswers: ["mende"] },
        { type: "text", value: " Industrialisierung d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Lebensmittelproduktion d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " westlichen Län" },
        { type: "missing", officialAnswers: ["der"] },
        { type: "text", value: ", der sogena" },
        { type: "missing", officialAnswers: ["nnten"] },
        { type: "text", value: " ersten We" },
        { type: "missing", officialAnswers: ["lt"] },
        { type: "text", value: ", macht au" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " vor d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Nahrung f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " unsere Hausti" },
        { type: "missing", officialAnswers: ["ere"] },
        { type: "text", value: " nicht ha" },
        { type: "missing", officialAnswers: ["lt"] },
        { type: "text", value: ": Zubereitetes Fut" },
        { type: "missing", officialAnswers: ["ter"] },
        { type: "text", value: " ist i" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " Überfluss u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " in d" },
        { type: "missing", officialAnswers: ["en"] },
        { type: "text", value: " unterschiedlichsten For" },
        { type: "missing", officialAnswers: ["men"] },
        { type: "text", value: " in Gesch" },
        { type: "missing", officialAnswers: ["äften"] },
        { type: "text", value: " für Tierfut" },
        { type: "missing", officialAnswers: ["ter"] },
        { type: "text", value: " erhältlich. E" },
        { type: "missing", officialAnswers: ["in"] },
        { type: "text", value: " Blick a" },
        { type: "missing", officialAnswers: ["uf"] },
        { type: "text", value: " die Zutatenlis" },
        { type: "missing", officialAnswers: ["ten"] },
        { type: "text", value: " enthüllt Erschre" },
        { type: "missing", officialAnswers: ["ckendes"] },
        { type: "text", value: ": Meist ha" },
        { type: "missing", officialAnswers: ["ben"] },
        { type: "text", value: " die Futtersor" },
        { type: "missing", officialAnswers: ["ten"] },
        { type: "text", value: " mit d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " artgerechten Ernäh" },
        { type: "missing", officialAnswers: ["rung"] },
        { type: "text", value: " eines Haustie" },
        { type: "missing", officialAnswers: ["res"] },
        { type: "text", value: " nicht me" },
        { type: "missing", officialAnswers: ["hr"] },
        { type: "text", value: " allzu vi" },
        { type: "missing", officialAnswers: ["el"] },
        { type: "text", value: " zu t" },
        { type: "missing", officialAnswers: ["un"] },
        { type: "text", value: ". Reine Fleischfres" },
        { type: "missing", officialAnswers: ["ser"] },
        { type: "text", value: " wie Kat" },
        { type: "missing", officialAnswers: ["zen"] },
        { type: "text", value: " erhalten i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " Fertigfutter z" },
        { type: "missing", officialAnswers: ["um"] },
        { type: "text", value: " Beispiel se" },
        { type: "missing", officialAnswers: ["hr"] },
        { type: "text", value: " häufig ei" },
        { type: "missing", officialAnswers: ["nen"] },
        { type: "text", value: " Brei a" },
        { type: "missing", officialAnswers: ["us"] },
        { type: "text", value: " Asche, Ma" },
        { type: "missing", officialAnswers: ["is"] },
        { type: "text", value: " oder So" },
        { type: "missing", officialAnswers: ["ja"] },
        { type: "text", value: " mit n" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " minimalem Fleischant" },
        { type: "missing", officialAnswers: ["eil"] },
        { type: "text", value: ". Tierhalter ge" },
        { type: "missing", officialAnswers: ["hen"] },
        { type: "text", value: " deswegen inzwi" },
        { type: "missing", officialAnswers: ["schen"] },
        { type: "text", value: " oft z" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " sogenannten Rohfütte" },
        { type: "missing", officialAnswers: ["rung"] },
        { type: "text", value: " über, u" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " ihren Tie" },
        { type: "missing", officialAnswers: ["ren"] },
        { type: "text", value: " ein mögl" },
        { type: "missing", officialAnswers: ["ichst"] },
        { type: "text", value: " artgerechtes Le" },
        { type: "missing", officialAnswers: ["ben"] },
        { type: "text", value: " zu ermög" },
        { type: "missing", officialAnswers: ["lichen"] },
        { type: "text", value: "." },
      ],
    },
  },
  {
    id: 71,
    name: "Wappen – historische „Ausweise“",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Wap" },
        { type: "missing", officialAnswers: ["pen"] },
        { type: "text", value: " sind i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " Deutschland übe" },
        { type: "missing", officialAnswers: ["rall"] },
        { type: "text", value: " zu fin" },
        { type: "missing", officialAnswers: ["den"] },
        { type: "text", value: ": Bundeslän" },
        { type: "missing", officialAnswers: ["der"] },
        { type: "text", value: ", Städte u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " teilweise au" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " alteingesessene od" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " adlige Fami" },
        { type: "missing", officialAnswers: ["lien"] },
        { type: "text", value: " verfügen üb" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " ein sol" },
        { type: "missing", officialAnswers: ["ches"] },
        { type: "text", value: " Identifikationssymbol, d" },
        { type: "missing", officialAnswers: ["as"] },
        { type: "text", value: " meist i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " Form ei" },
        { type: "missing", officialAnswers: ["nes"] },
        { type: "text", value: " Schildes geha" },
        { type: "missing", officialAnswers: ["lten"] },
        { type: "text", value: " ist. I" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " früheren Zei" },
        { type: "missing", officialAnswers: ["ten"] },
        { type: "text", value: " wie au" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " heute dienen Wappen z" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " Identifikation d" },
        { type: "missing", officialAnswers: ["es"] },
        { type: "text", value: " Landes od" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " der Körpers" },
        { type: "missing", officialAnswers: ["chaft"] },
        { type: "text", value: ", die e" },
        { type: "missing", officialAnswers: ["s"] },
        { type: "text", value: " trägt. Wap" },
        { type: "missing", officialAnswers: ["pen"] },
        { type: "text", value: " sind mei" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: " mehrfarbig gest" },
        { type: "missing", officialAnswers: ["altet"] },
        { type: "text", value: " und entha" },
        { type: "missing", officialAnswers: ["lten"] },
        { type: "text", value: " in vie" },
        { type: "missing", officialAnswers: ["len"] },
        { type: "text", value: " Fällen stilis" },
        { type: "missing", officialAnswers: ["ierte"] },
        { type: "text", value: " Pflanzen, Ti" },
        { type: "missing", officialAnswers: ["ere"] },
        { type: "text", value: " oder Gegenstä" },
        { type: "missing", officialAnswers: ["nde"] },
        { type: "text", value: ", die f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " die symboli" },
        { type: "missing", officialAnswers: ["sierte"] },
        { type: "text", value: " Körperschaft typ" },
        { type: "missing", officialAnswers: ["isch"] },
        { type: "text", value: " sind u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " einen ho" },
        { type: "missing", officialAnswers: ["hen"] },
        { type: "text", value: " Wiedererkennungswert besi" },
        { type: "missing", officialAnswers: ["tzen"] },
        { type: "text", value: ". Ursprünglich dien" },
        { type: "missing", officialAnswers: ["ten"] },
        { type: "text", value: " Wappen a" },
        { type: "missing", officialAnswers: ["uf"] },
        { type: "text", value: " Schildern u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Helmen v" },
        { type: "missing", officialAnswers: ["on"] },
        { type: "text", value: " Rittern z" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " besseren Identif" },
        { type: "missing", officialAnswers: ["ikation"] },
        { type: "text", value: " in Kampfgesch" },
        { type: "missing", officialAnswers: ["ehen"] },
        { type: "text", value: ". In die" },
        { type: "missing", officialAnswers: ["ser"] },
        { type: "text", value: " martialischen Fo" },
        { type: "missing", officialAnswers: ["rm"] },
        { type: "text", value: " der Identif" },
        { type: "missing", officialAnswers: ["ikation"] },
        { type: "text", value: " werden s" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " jedoch he" },
        { type: "missing", officialAnswers: ["ute"] },
        { type: "text", value: " nicht mehr genutzt." },
      ],
    },
  },
  {
    id: 72,
    name: "Nutzen statt besitzen",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Mens" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " stellen si" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " in uns" },
        { type: "missing", officialAnswers: ["erer"] },
        { type: "text", value: " Gesellschaft d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " scheinbar grenze" },
        { type: "missing", officialAnswers: ["nlosen"] },
        { type: "text", value: " technischen Möglich" },
        { type: "missing", officialAnswers: ["keiten"] },
        { type: "text", value: " und d" },
        { type: "missing", officialAnswers: ["es"] },
        { type: "text", value: " Überflusses im" },
        { type: "missing", officialAnswers: ["mer"] },
        { type: "text", value: " häufiger d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Frage, o" },
        { type: "missing", officialAnswers: ["b"] },
        { type: "text", value: " sie besti" },
        { type: "missing", officialAnswers: ["mmte"] },
        { type: "text", value: " Dinge f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " ihr tägli" },
        { type: "missing", officialAnswers: ["ches"] },
        { type: "text", value: " Leben wirk" },
        { type: "missing", officialAnswers: ["lich"] },
        { type: "text", value: " besitzen müs" },
        { type: "missing", officialAnswers: ["sen"] },
        { type: "text", value: " oder o" },
        { type: "missing", officialAnswers: ["b"] },
        { type: "text", value: " für s" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " ein zeit" },
        { type: "missing", officialAnswers: ["lich"] },
        { type: "text", value: " beschränktes Nutzungsre" },
        { type: "missing", officialAnswers: ["cht"] },
        { type: "text", value: " nicht ausrei" },
        { type: "missing", officialAnswers: ["chend"] },
        { type: "text", value: " ist. S" },
        { type: "missing", officialAnswers: ["o"] },
        { type: "text", value: " teilen si" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " Menschen un" },
        { type: "missing", officialAnswers: ["ter"] },
        { type: "text", value: " anderem Eink" },
        { type: "missing", officialAnswers: ["äufe"] },
        { type: "text", value: ", Fernseher, Au" },
        { type: "missing", officialAnswers: ["tos"] },
        { type: "text", value: ", Waschmaschinen od" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " auch Wohnu" },
        { type: "missing", officialAnswers: ["ngen"] },
        { type: "text", value: ", wenn di" },
        { type: "missing", officialAnswers: ["ese"] },
        { type: "text", value: " nicht ununterb" },
        { type: "missing", officialAnswers: ["rochen"] },
        { type: "text", value: " von derse" },
        { type: "missing", officialAnswers: ["lben"] },
        { type: "text", value: " Person benö" },
        { type: "missing", officialAnswers: ["tigt"] },
        { type: "text", value: " werden. Beson" },
        { type: "missing", officialAnswers: ["ders"] },
        { type: "text", value: " beliebt – u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " dies insbes" },
        { type: "missing", officialAnswers: ["ondere"] },
        { type: "text", value: " in Großstäd" },
        { type: "missing", officialAnswers: ["ten"] },
        { type: "text", value: " – ist d" },
        { type: "missing", officialAnswers: ["as"] },
        { type: "text", value: " sogenannte Carshar" },
        { type: "missing", officialAnswers: ["ing"] },
        { type: "text", value: ", bei d" },
        { type: "missing", officialAnswers: ["em"] },
        { type: "text", value: " meist ei" },
        { type: "missing", officialAnswers: ["ne"] },
        { type: "text", value: " Firma, o" },
        { type: "missing", officialAnswers: ["ft"] },
        { type: "text", value: " aber au" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " Privatpersonen f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " eine monat" },
        { type: "missing", officialAnswers: ["liche"] },
        { type: "text", value: " Gebühr Au" },
        { type: "missing", officialAnswers: ["tos"] },
        { type: "text", value: " zur Verfü" },
        { type: "missing", officialAnswers: ["gung"] },
        { type: "text", value: " stellen, d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " dann f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " bestimmte Ta" },
        { type: "missing", officialAnswers: ["ge"] },
        { type: "text", value: " oder au" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " nur Stu" },
        { type: "missing", officialAnswers: ["nden"] },
        { type: "text", value: " buchbar sind." },
      ],
    },
  },
  {
    id: 73,
    name: "Multiresistente Bakterien",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Unter ande" },
        { type: "missing", officialAnswers: ["rem"] },
        { type: "text", value: " durch d" },
        { type: "missing", officialAnswers: ["en"] },
        { type: "text", value: " verfrühten od" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " fehlerhaften Eins" },
        { type: "missing", officialAnswers: ["atz"] },
        { type: "text", value: " von Antibi" },
        { type: "missing", officialAnswers: ["otika"] },
        { type: "text", value: " im Ka" },
        { type: "missing", officialAnswers: ["mpf"] },
        { type: "text", value: " gegen Infe" },
        { type: "missing", officialAnswers: ["kte"] },
        { type: "text", value: " haben krankheitserreg" },
        { type: "missing", officialAnswers: ["ende"] },
        { type: "text", value: " Keime teilw" },
        { type: "missing", officialAnswers: ["eise"] },
        { type: "text", value: " sogenannte Multiresist" },
        { type: "missing", officialAnswers: ["enzen"] },
        { type: "text", value: " ausgeprägt, d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " ihre schulmedizi" },
        { type: "missing", officialAnswers: ["nische"] },
        { type: "text", value: " Bekämpfung bein" },
        { type: "missing", officialAnswers: ["ahe"] },
        { type: "text", value: " unmöglich mac" },
        { type: "missing", officialAnswers: ["hen"] },
        { type: "text", value: " und Einrich" },
        { type: "missing", officialAnswers: ["tungen"] },
        { type: "text", value: " der Gesundheitspfl" },
        { type: "missing", officialAnswers: ["ege"] },
        { type: "text", value: " im Fa" },
        { type: "missing", officialAnswers: ["lle"] },
        { type: "text", value: " von Epide" },
        { type: "missing", officialAnswers: ["mien"] },
        { type: "text", value: " vor ei" },
        { type: "missing", officialAnswers: ["ne"] },
        { type: "text", value: " beinahe unüberwi" },
        { type: "missing", officialAnswers: ["ndbare"] },
        { type: "text", value: " Aufgabe stel" },
        { type: "missing", officialAnswers: ["len"] },
        { type: "text", value: ". Insbesondere i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " Krankenhäusern bre" },
        { type: "missing", officialAnswers: ["iten"] },
        { type: "text", value: " sich multiresis" },
        { type: "missing", officialAnswers: ["tente"] },
        { type: "text", value: " Erreger me" },
        { type: "missing", officialAnswers: ["ist"] },
        { type: "text", value: " schnell u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " ungehindert a" },
        { type: "missing", officialAnswers: ["us"] },
        { type: "text", value: " und ford" },
        { type: "missing", officialAnswers: ["ern"] },
        { type: "text", value: " dabei ni" },
        { type: "missing", officialAnswers: ["cht"] },
        { type: "text", value: " selten Todesop" },
        { type: "missing", officialAnswers: ["fer"] },
        { type: "text", value: ". Aber au" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " außerhalb v" },
        { type: "missing", officialAnswers: ["on"] },
        { type: "text", value: " Krankenhäusern verbr" },
        { type: "missing", officialAnswers: ["eiten"] },
        { type: "text", value: " sich Infe" },
        { type: "missing", officialAnswers: ["kte"] },
        { type: "text", value: " oft m" },
        { type: "missing", officialAnswers: ["it"] },
        { type: "text", value: " furchterregender Geschwin" },
        { type: "missing", officialAnswers: ["digkeit"] },
        { type: "text", value: " und las" },
        { type: "missing", officialAnswers: ["sen"] },
        { type: "text", value: " an ih" },
        { type: "missing", officialAnswers: ["nen"] },
        { type: "text", value: " erkrankte Mens" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " nicht sel" },
        { type: "missing", officialAnswers: ["ten"] },
        { type: "text", value: " für meh" },
        { type: "missing", officialAnswers: ["rere"] },
        { type: "text", value: " Wochen kr" },
        { type: "missing", officialAnswers: ["ank"] },
        { type: "text", value: " im Be" },
        { type: "missing", officialAnswers: ["tt"] },
        { type: "text", value: " liegen. D" },
        { type: "missing", officialAnswers: ["as"] },
        { type: "text", value: " markanteste Charakte" },
        { type: "missing", officialAnswers: ["ristikum"] },
        { type: "text", value: " solcher Krankheitswel" },
        { type: "missing", officialAnswers: ["len"] },
        { type: "text", value: " ist, da" },
        { type: "missing", officialAnswers: ["ss"] },
        { type: "text", value: " beinahe ke" },
        { type: "missing", officialAnswers: ["ine"] },
        { type: "text", value: " Therapie d" },
        { type: "missing", officialAnswers: ["en"] },
        { type: "text", value: " Kranken Linde" },
        { type: "missing", officialAnswers: ["rung"] },
        { type: "text", value: " verschafft." },
      ],
    },
  },
  {
    id: 74,
    name: "Die Entstehungsgeschichte des Christopher Street Days",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Der Christopher Street Day ist ein Gedenk- u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Demonstrationstag ho" },
        { type: "missing", officialAnswers: ["mo-"] },
        { type: "text", value: ", bi- u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " transsexueller Mens" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " in Deutschla" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: ", der i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " vielen Großstä" },
        { type: "missing", officialAnswers: ["dten"] },
        { type: "text", value: " mit Demonstr" },
        { type: "missing", officialAnswers: ["ationen"] },
        { type: "text", value: " und anschli" },
        { type: "missing", officialAnswers: ["eßenden"] },
        { type: "text", value: " Straßenfesten gefe" },
        { type: "missing", officialAnswers: ["iert"] },
        { type: "text", value: " wird. D" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Name „Christ" },
        { type: "missing", officialAnswers: ["opher"] },
        { type: "text", value: " Street D" },
        { type: "missing", officialAnswers: ["ay"] },
        { type: "text", value: "“ ist n" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " in Deutschla" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " üblich. E" },
        { type: "missing", officialAnswers: ["r"] },
        { type: "text", value: " verweist a" },
        { type: "missing", officialAnswers: ["uf"] },
        { type: "text", value: " einen Aufsta" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Homosexueller ge" },
        { type: "missing", officialAnswers: ["gen"] },
        { type: "text", value: " polizeiliche Razz" },
        { type: "missing", officialAnswers: ["ien"] },
        { type: "text", value: " in N" },
        { type: "missing", officialAnswers: ["ew"] },
        { type: "text", value: " York Ci" },
        { type: "missing", officialAnswers: ["ty"] },
        { type: "text", value: " 1969, b" },
        { type: "missing", officialAnswers: ["ei"] },
        { type: "text", value: " dem d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Bar „Stonewall Inn“, d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " in d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Christopher Str" },
        { type: "missing", officialAnswers: ["eet"] },
        { type: "text", value: " im Stadtvier" },
        { type: "missing", officialAnswers: ["tel"] },
        { type: "text", value: " Greenwich l" },
        { type: "missing", officialAnswers: ["ag"] },
        { type: "text", value: ", zum Zent" },
        { type: "missing", officialAnswers: ["rum"] },
        { type: "text", value: " des Gesch" },
        { type: "missing", officialAnswers: ["ehens"] },
        { type: "text", value: " wurde. D" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Demonstrationen z" },
        { type: "missing", officialAnswers: ["um"] },
        { type: "text", value: " Christopher Str" },
        { type: "missing", officialAnswers: ["eet"] },
        { type: "text", value: " Day i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " Deutschland erin" },
        { type: "missing", officialAnswers: ["nern"] },
        { type: "text", value: " an d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " nach w" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " vor vorha" },
        { type: "missing", officialAnswers: ["ndene"] },
        { type: "text", value: " Ausgrenzung, Diskrimi" },
        { type: "missing", officialAnswers: ["nierung"] },
        { type: "text", value: " und Gew" },
        { type: "missing", officialAnswers: ["alt"] },
        { type: "text", value: " gegen ho" },
        { type: "missing", officialAnswers: ["mo-"] },
        { type: "text", value: ", bi- u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " transsexuelle Mens" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " und ha" },
        { type: "missing", officialAnswers: ["ben"] },
        { type: "text", value: " die Gleichstel" },
        { type: "missing", officialAnswers: ["lung"] },
        { type: "text", value: " der Rec" },
        { type: "missing", officialAnswers: ["hte"] },
        { type: "text", value: " dieser Grup" },
        { type: "missing", officialAnswers: ["pen"] },
        { type: "text", value: " mit d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " heterosexuellen Bevölk" },
        { type: "missing", officialAnswers: ["erung"] },
        { type: "text", value: " zum Ziel." },
      ],
    },
  },
  {
    id: 75,
    name: "Stress",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Das Wo" },
        { type: "missing", officialAnswers: ["rt"] },
        { type: "text", value: " Stress i" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: " eines d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " am häufi" },
        { type: "missing", officialAnswers: ["gsten"] },
        { type: "text", value: " verwendeten Substa" },
        { type: "missing", officialAnswers: ["ntive"] },
        { type: "text", value: " unserer Ze" },
        { type: "missing", officialAnswers: ["it"] },
        { type: "text", value: " und i" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " sozialen Umfe" },
        { type: "missing", officialAnswers: ["ld"] },
        { type: "text", value: " gleichermaßen z" },
        { type: "missing", officialAnswers: ["um"] },
        { type: "text", value: " Synonym f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " die Wichti" },
        { type: "missing", officialAnswers: ["gkeit"] },
        { type: "text", value: " der Arb" },
        { type: "missing", officialAnswers: ["eit"] },
        { type: "text", value: " einer Per" },
        { type: "missing", officialAnswers: ["son"] },
        { type: "text", value: " geworden. D" },
        { type: "missing", officialAnswers: ["as"] },
        { type: "text", value: " Leben, d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Arbeit, d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " neue Auft" },
        { type: "missing", officialAnswers: ["rag"] },
        { type: "text", value: ": Alles i" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: " nur ei" },
        { type: "missing", officialAnswers: ["ner"] },
        { type: "text", value: " Erwähnung we" },
        { type: "missing", officialAnswers: ["rt"] },
        { type: "text", value: ", wenn e" },
        { type: "missing", officialAnswers: ["s"] },
        { type: "text", value: " stressig i" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: ". Stress i" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: " jedoch ei" },
        { type: "missing", officialAnswers: ["ne"] },
        { type: "text", value: " Belastung f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " Geist u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Körper u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " kann insbes" },
        { type: "missing", officialAnswers: ["ondere"] },
        { type: "text", value: " in sei" },
        { type: "missing", officialAnswers: ["ner"] },
        { type: "text", value: " negativen Fo" },
        { type: "missing", officialAnswers: ["rm"] },
        { type: "text", value: " alle Funkt" },
        { type: "missing", officialAnswers: ["ionen"] },
        { type: "text", value: " des Körp" },
        { type: "missing", officialAnswers: ["ers"] },
        { type: "text", value: " beeinträchtigen. Du" },
        { type: "missing", officialAnswers: ["rch"] },
        { type: "text", value: " ihn verurs" },
        { type: "missing", officialAnswers: ["achte"] },
        { type: "text", value: " Beschwerden reic" },
        { type: "missing", officialAnswers: ["hen"] },
        { type: "text", value: " von Muskelverspan" },
        { type: "missing", officialAnswers: ["nungen"] },
        { type: "text", value: " über Heißhun" },
        { type: "missing", officialAnswers: ["ger"] },
        { type: "text", value: " und Verdauungsstöru" },
        { type: "missing", officialAnswers: ["ngen"] },
        { type: "text", value: " bis h" },
        { type: "missing", officialAnswers: ["in"] },
        { type: "text", value: " zu Hörstu" },
        { type: "missing", officialAnswers: ["rz"] },
        { type: "text", value: ", Bluthochdruck u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Hauterkrankungen. Negat" },
        { type: "missing", officialAnswers: ["iven"] },
        { type: "text", value: " Stressoren (äuß" },
        { type: "missing", officialAnswers: ["eren"] },
        { type: "text", value: " Reizen, d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " den Mens" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " zu ei" },
        { type: "missing", officialAnswers: ["ner"] },
        { type: "text", value: " negativen Stressreak" },
        { type: "missing", officialAnswers: ["tion"] },
        { type: "text", value: " animieren) gi" },
        { type: "missing", officialAnswers: ["lt"] },
        { type: "text", value: " es al" },
        { type: "missing", officialAnswers: ["so"] },
        { type: "text", value: " möglichst kontro" },
        { type: "missing", officialAnswers: ["lliert"] },
        { type: "text", value: " und entspannt zu begegnen." },
      ],
    },
  },
];
