const tests = [
  {
    id: 65,
    name: "Die Gebrüder Grimm",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "D" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Ende d" },
        { type: "missing", officialAnswers: ["es"] },
        { type: "text", value: " siebzehnten Jahrhund" },
        { type: "missing", officialAnswers: ["erts"] },
        { type: "text", value: " geborenen Brü" },
        { type: "missing", officialAnswers: ["der"] },
        { type: "text", value: " Jacob u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Wilhelm Gri" },
        { type: "missing", officialAnswers: ["mm"] },
        { type: "text", value: " sind vie" },
        { type: "missing", officialAnswers: ["len"] },
        { type: "text", value: " Deutschen vorwi" },
        { type: "missing", officialAnswers: ["egend"] },
        { type: "text", value: " als Verfa" },
        { type: "missing", officialAnswers: ["sser"] },
        { type: "text", value: " der Märchensamm" },
        { type: "missing", officialAnswers: ["lung"] },
        { type: "text", value: " „Kinder- u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Hausmärchen“ beka" },
        { type: "missing", officialAnswers: ["nnt"] },
        { type: "text", value: ". Was vie" },
        { type: "missing", officialAnswers: ["len"] },
        { type: "text", value: " ihrer Le" },
        { type: "missing", officialAnswers: ["ser"] },
        { type: "text", value: " jedoch weni" },
        { type: "missing", officialAnswers: ["ger"] },
        { type: "text", value: " bewusst i" },
        { type: "missing", officialAnswers: ["st"] },
        { type: "text", value: ", sind ih" },
        { type: "missing", officialAnswers: ["re"] },
        { type: "text", value: " Verdienste u" },
        { type: "missing", officialAnswers: ["m"] },
        { type: "text", value: " die deut" },
        { type: "missing", officialAnswers: ["sche"] },
        { type: "text", value: " Sprache, a" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " der ih" },
        { type: "missing", officialAnswers: ["nen"] },
        { type: "text", value: " als Sprachwissensc" },
        { type: "missing", officialAnswers: ["haftler"] },
        { type: "text", value: " sehr vi" },
        { type: "missing", officialAnswers: ["el"] },
        { type: "text", value: " gelegen w" },
        { type: "missing", officialAnswers: ["ar"] },
        { type: "text", value: ". So zeic" },
        { type: "missing", officialAnswers: ["hnen"] },
        { type: "text", value: " die a" },
        { type: "missing", officialAnswers: ["us"] },
        { type: "text", value: " Hanau stamm" },
        { type: "missing", officialAnswers: ["enden"] },
        { type: "text", value: " Brüder Gri" },
        { type: "missing", officialAnswers: ["mm"] },
        { type: "text", value: " beispielsweise f" },
        { type: "missing", officialAnswers: ["ür"] },
        { type: "text", value: " die Erstel" },
        { type: "missing", officialAnswers: ["lung"] },
        { type: "text", value: " der ers" },
        { type: "missing", officialAnswers: ["ten"] },
        { type: "text", value: " deutschen Gram" },
        { type: "missing", officialAnswers: ["matik"] },
        { type: "text", value: " verantwortlich. D" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " eine d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Brüder, Ja" },
        { type: "missing", officialAnswers: ["cob"] },
        { type: "text", value: ", machte si" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " dabei insbes" },
        { type: "missing", officialAnswers: ["ondere"] },
        { type: "text", value: " mit d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Erforschung d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " indogermanischen Sprachherk" },
        { type: "missing", officialAnswers: ["unft"] },
        { type: "text", value: " des Deuts" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " einen Na" },
        { type: "missing", officialAnswers: ["men"] },
        { type: "text", value: ". Die Tats" },
        { type: "missing", officialAnswers: ["ache"] },
        { type: "text", value: ", dass e" },
        { type: "missing", officialAnswers: ["s"] },
        { type: "text", value: " heute i" },
        { type: "missing", officialAnswers: ["n"] },
        { type: "text", value: " beinahe je" },
        { type: "missing", officialAnswers: ["der"] },
        { type: "text", value: " Stadt ei" },
        { type: "missing", officialAnswers: ["ne"] },
        { type: "text", value: " Gebrüder-Grimm-Sch" },
        { type: "missing", officialAnswers: ["ule"] },
        { type: "text", value: " gibt, verdeu" },
        { type: "missing", officialAnswers: ["tlicht"] },
        { type: "text", value: " ihre imme" },
        { type: "missing", officialAnswers: ["nse"] },
        { type: "text", value: " Bedeutung für das deutsche Kulturgut." },
      ],
    },
  },
  {
    id: 66,
    name: "PKW-Maut",
    content: {
      type: "fb",
      items: [
        { type: "text", value: "Maut, s" },
        { type: "missing", officialAnswers: ["o"] },
        { type: "text", value: " nennt si" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " in Deutschla" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " eine allge" },
        { type: "missing", officialAnswers: ["meine"] },
        { type: "text", value: " Abgabe, d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " zur Nutz" },
        { type: "missing", officialAnswers: ["ung"] },
        { type: "text", value: " des Autobahnnet" },
        { type: "missing", officialAnswers: ["zes"] },
        { type: "text", value: " mit Kraftfahrzeu" },
        { type: "missing", officialAnswers: ["gen"] },
        { type: "text", value: " berechtigt. Vi" },
        { type: "missing", officialAnswers: ["ele"] },
        { type: "text", value: " Länder Euro" },
        { type: "missing", officialAnswers: ["pas"] },
        { type: "text", value: " nutzen ber" },
        { type: "missing", officialAnswers: ["eits"] },
        { type: "text", value: " seit Lan" },
        { type: "missing", officialAnswers: ["gem"] },
        { type: "text", value: " diese Fo" },
        { type: "missing", officialAnswers: ["rm"] },
        { type: "text", value: " der Geb" },
        { type: "missing", officialAnswers: ["ühr,"] },
        { type: "text", value: " um d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " notwendigen Instandhaltu" },
        { type: "missing", officialAnswers: ["ngen"] },
        { type: "text", value: " ihres Straßensyst" },
        { type: "missing", officialAnswers: ["ems"] },
        { type: "text", value: " zu finanz" },
        { type: "missing", officialAnswers: ["ieren"] },
        { type: "text", value: ". In d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Bundesrepublik gi" },
        { type: "missing", officialAnswers: ["bt"] },
        { type: "text", value: " es d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Maut jed" },
        { type: "missing", officialAnswers: ["och"] },
        { type: "text", value: " bislang n" },
        { type: "missing", officialAnswers: ["ur"] },
        { type: "text", value: " für LK" },
        { type: "missing", officialAnswers: ["Ws."] },
        { type: "text", value: " Ab 2016 sol" },
        { type: "missing", officialAnswers: ["lte"] },
        { type: "text", value: " nun na" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " Plänen d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Regierung au" },
        { type: "missing", officialAnswers: ["ch"] },
        { type: "text", value: " für PK" },
        { type: "missing", officialAnswers: ["Ws"] },
        { type: "text", value: " eine Ma" },
        { type: "missing", officialAnswers: ["ut"] },
        { type: "text", value: " eingeführt wer" },
        { type: "missing", officialAnswers: ["den"] },
        { type: "text", value: ", um d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " marode Finanz" },
        { type: "missing", officialAnswers: ["ierung"] },
        { type: "text", value: " der deuts" },
        { type: "missing", officialAnswers: ["chen"] },
        { type: "text", value: " Autobahnen aufzube" },
        { type: "missing", officialAnswers: ["ssern"] },
        { type: "text", value: ". Kritiker wand" },
        { type: "missing", officialAnswers: ["ten"] },
        { type: "text", value: " jedoch e" },
        { type: "missing", officialAnswers: ["in"] },
        { type: "text", value: ", dass d" },
        { type: "missing", officialAnswers: ["ie"] },
        { type: "text", value: " Art u" },
        { type: "missing", officialAnswers: ["nd"] },
        { type: "text", value: " Weise d" },
        { type: "missing", officialAnswers: ["er"] },
        { type: "text", value: " Abgabe kei" },
        { type: "missing", officialAnswers: ["ne"] },
        { type: "text", value: " effektive Aufbes" },
        { type: "missing", officialAnswers: ["serung"] },
        { type: "text", value: " der Fina" },
        { type: "missing", officialAnswers: ["nzen"] },
        { type: "text", value: " des Verkehrsminist" },
        { type: "missing", officialAnswers: ["eriums"] },
        { type: "text", value: " zur Fo" },
        { type: "missing", officialAnswers: ["lge"] },
        { type: "text", value: " haben we" },
        { type: "missing", officialAnswers: ["rde"] },
        { type: "text", value: ". Zud" },
        { type: "missing", officialAnswers: ["em"] },
        { type: "text", value: " wird inzwi" },
        { type: "missing", officialAnswers: ["schen"] },
        { type: "text", value: " die Rechtmäß" },
        { type: "missing", officialAnswers: ["igkeit"] },
        { type: "text", value: " der Ma" },
        { type: "missing", officialAnswers: ["ut"] },
        { type: "text", value: " nach EU-Recht geprüft." },
      ],
    },
  },
];
